blog/urls.py
from django.urls import path
from . import views
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

app_name = 'blog'

sitemaps = {
    'posts':PostSitemap,
}
from .feeds import LatesPostsFeed
urlpatterns = [
    # F_B_V
    path('', views.list_of_posts , name='post_list'),
    path('tag/<slug:tag_slug>/' , views.list_of_posts , name='post_list_by_tag'),
    # URL For the Single post
    path('<int:year>/<int:month>/<int:day>/<slug:post>/' , views.post_details , name='post_detail'),
    # URL For share post with email 
    path('<int:post_id>/share/', views.post_share ,name='post_share'),
    # URL For commnets
    path('<int:post_id>/comment/', views.post_comment , name='post_comment'),
    # Sitemaps URL
    path('sitemap.xml', sitemap, {'sitemaps':sitemaps} , name='django.contrib.sitemaps.views.sitemap'),
    path('feed/' , LatesPostsFeed() , name='post_feed'),
    # Search URL
    path('search/' , views.post_search, name='post_search'),

]

main_blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path , include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls',namespace='blog'))
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# urlpatterns += staticfiles_urlpatterns

templates/includes/comment_form.html
{% comment %} comment form  {% endcomment %}
<div class="comment-form-wrap pt-5">
    <h3 class="mb-5">Add a New Comment</h3>
    <form action="{% url 'blog:post_comment' post.id %}" method='POST'>
      <div class="form-group">
        {{form.as_p}}
        {% csrf_token %}
      </div>
     

      <div class="form-group">
        <input type="submit" value="Add Comment" class="btn btn-primary btn-md">
      </div>

    </form>
  </div>
</div>