blog/urls.py
from django.urls import path
from . import views
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

app_name = 'blog'

sitemaps = {
    'posts':PostSitemap,
}
from .feeds import LatesPostsFeed
urlpatterns = [
    # F_B_V
    path('', views.list_of_posts , name='post_list'),
    path('tag/<slug:tag_slug>/' , views.list_of_posts , name='post_list_by_tag'),
    # URL For the Single post
    path('<int:year>/<int:month>/<int:day>/<slug:post>/' , views.post_details , name='post_detail'),
    # URL For share post with email 
    path('<int:post_id>/share/', views.post_share ,name='post_share'),
    # URL For commnets
    path('<int:post_id>/comment/', views.post_comment , name='post_comment'),
    # Sitemaps URL
    path('sitemap.xml', sitemap, {'sitemaps':sitemaps} , name='django.contrib.sitemaps.views.sitemap'),
    path('feed/' , LatesPostsFeed() , name='post_feed'),
    # Search URL
    path('search/' , views.post_search, name='post_search'),

]

main_blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path , include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls',namespace='blog'))
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# urlpatterns += staticfiles_urlpatterns

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager 




class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)


class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250 , unique_for_date='publish') # URLS frendliy for SEO
    auther = models.ForeignKey(User ,on_delete=models.CASCADE , related_name='blog_posts') # Meny to one relation
    image = models.ImageField(upload_to='images/%Y/%M/%d' , blank=True , null=True )
    content = models.TextField()
    publish =  models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2 , choices=Status.choices , default=Status.DRAFT)

    published = PublishedManager() # custome manager
    tags = TaggableManager()

    class Meta:
        ordering = ['-publish']      # in this we tell django that is should sort results by the publish field
        indexes = [models.Index(fields=['-publish'])]  # Indexes can improve database query performance


    def __str__(self) -> str:
        return self.title
    

    def get_absolute_url(self):
        return reverse('blog:post_detail' , args=[self.publish.year, self.publish.month , self.publish.day, self.slug])
    

    
# Many to one relational 
# comment one  | post many 

class Comment(models.Model):
    post = models.ForeignKey(Post , on_delete=models.CASCADE , related_name='comments')
    name = models.CharField(max_length=100)
    email = models.EmailField()
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)


    class Meta:
        ordering = ['-created']
        indexes = [
            models.Index(fields=['-created'])
        ]   

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'    

blog/forms.py
from django import forms 
from .models import Comment





class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=50 , widget=forms.TextInput(attrs={"class":'form-control', 'placeholder':'Enter Your Name'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control', 'placeholder':'Enter Your Email'}))
    to = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control', 'placeholder':'Enter E-mail'}))
    comments = forms.CharField(required=False , widget=forms.Textarea(attrs={'class':'form-control', 'placeholder':'Enter Your Notes!'}))




class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'content')
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control'}),
        }



class SearchForm(forms.Form):
    query = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control mr-sm-2", 'placeholder': 'Search'}))

blog/views.py
from django.shortcuts import render , get_object_or_404
from .models import Post , Comment
from django.core.paginator import Paginator , EmptyPage , PageNotAnInteger
from django.views.generic import ListView
from.forms import EmailPostForm , CommentForm , SearchForm
from django.core.mail import send_mail
from django.views.decorators.http import require_POST
from taggit.models import Tag
from django.db.models import Count
from django.contrib.postgres.search import SearchVector , SearchQuery , SearchRank


# F_B_V 
def list_of_posts(request , tag_slug=None):
    posts_list = Post.published.all().order_by('-created')
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag , slug=tag_slug) # git the tag object with the tag_slug 
        posts_list = posts_list.filter(tags__in=[tag])

    paginator = Paginator(posts_list , 3) # Here, we create a Paginator object named paginator with a page size of 3 posts per page.
    page_number = request.GET.get('page' , 1) # This line retrieves the value of the page parameter from the request's query string. If the parameter is not present, it defaults to 1.
    try:
       posts = paginator.page(page_number)
    except PageNotAnInteger:
        # If page_number is not an integer deliver the first page
        posts = paginator.page(1)  
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)     

    return render(request , 'blog/posts/list.html' ,{'posts':posts , 'tag':tag})


# C_B_V
# class PostListView(ListView):
#     """
#     Alternative Post List View
#     """
#     queryset = Post.published.all().order_by('-created')
#     context_object_name = 'posts'
#     paginate_by = 3
#     template_name = 'blog/posts/list.html'





def post_details(request , post , year , month , day):
    post = get_object_or_404(Post,status=Post.Status.PUBLISHED, publish__year=year , publish__month=month , publish__day=day,slug=post)
    # list of active comments for this post
    commetns = post.comments.filter(active=True)
    # form for users to comment
    form = CommentForm()

    # Tags
    post_tags_ids = post.tags.values_list('id' , flat=True) # retrive tubles with the value
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', 'publish')[:4]



    context = {
        'post':post,
        'form':form,
        'comments':commetns,
        'similar_posts': similar_posts,
    }
    return render(request, 'blog/posts/details.html', context)




def post_share(request , post_id):
    # retriver post by id 
    post = get_object_or_404(Post , id=post_id , status=Post.Status.PUBLISHED)
    sent = False
    if request.method == 'POST':
        form = EmailPostForm(request.POST) # form was submitted 
        if form.is_valid():
            # form fields passed validation
            cd = form.cleaned_data # this is a dict of form fields and their values
            # ...send email
            post_url = request.build_absolute_uri(post.get_absolute_url()) # post url 
            subject = f"{cd['name']} recommends you read"\
                      f'{post.title}'
            message = f"Read {post.title} at {post_url}\n\n"\
                      f"{cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject , message , 'motazfawzy73@gmail' ,[cd['to']])
            sent = True
            
    else:
        form = EmailPostForm() # if method is GET to return Empty form
    context = {
        "form":form,
        'post':post,
        'sent':sent,
    }    
    return render(request , 'blog/posts/share.html' , context)            



# Only allow POST requests for this view
@require_POST
def post_comment(request , post_id):
    post = get_object_or_404(Post , id=post_id , status=Post.Status.PUBLISHED)
    comment = None

    # A comment Was Post
    form = CommentForm(data=request.POST)
    if form.is_valid():
        # create a comment object without saveing it to the database
        comment = form.save(commit=False) 
        # Assign the post to the comment
        comment.post = post
        # save the comment to the database
        comment.save()
    context = {
        'form':form,
        'comment':comment,
        'post':post
    }    
    return render(request , 'blog/posts/comment.html' , context)






def post_search(request):
    form = SearchForm()
    query = None
    results = []

    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']

            search_vector = SearchVector('title', 'content', config='english') #search in model post and title and content fields
            search_qeuery = SearchQuery(query ,  config='english') # create object by query




            results = Post.published.annotate(
                search=search_vector,rank=SearchRank(search_vector,search_qeuery)
            ).filter(search=search_qeuery).order_by('-rank')
    context = {
        'form':form,
        'query':query,
        'results':results
    }        
    return render(request , 'blog/posts/search.html' , context)        

templates/blog/posts/comment.html
{% extends "blog/base.html" %}




{% block content %}

{% if comment %}

<div class="alert alert-success" role="alert">
    <h1 class="alert-heading">Your Comment has been added</h4>
    <hr>
  <p class="mb-0"><a href="{{ post.get_absolute_url }}"> <button type="button" class="btn btn-light">Back To The Post</button></a></p>
</div>
</div> 


{% else %}
{% include "includes/comment_form.html" %}
{% endif %}

{% endblock content %}

templates/blog/posts/details.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% load static %}

{% block content %}


<div class="lines-wrap">
    <div class="lines-inner">
      <div class="lines"></div>
    </div>
  </div>
  <!-- END lines -->


  <div class="site-mobile-menu site-navbar-target">
    <div class="site-mobile-menu-header">
      <div class="site-mobile-menu-close">
        <span class="icofont-close js-menu-toggle"></span>
      </div>
    </div>
    <div class="site-mobile-menu-body"></div>
  </div>


{% include "blog/parts/navbar.html" %}


  <div class="custom-hero">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-8">
          <h1 class="hero-heading">{{post.title}}</h1>
          <div  class="line js-line mx-auto mb-3 my-3"></div>
          <p class="sub-text"><b>Published :</b> {{post.publish}} By <b>{{post.auther}}</b> </p>
        </div>
      </div>
    </div>
  </div>

  <div class="site-section">
    <div class="container article">
      <div class="row justify-content-center align-items-stretch">

        <article class="col-lg-8 order-lg-2 px-lg-5">
          <p>{{post.content|markdown}}</p>

      

          <div class="pt-5 categories_tags ">
            <h1>Similar Posts:</h1>
            <ul>
            {% for post in similar_posts %}
            <li><h3><a href="{{post.get_absolute_url}}">{{post.title}}</a></h3></li>
           
            {% empty %}
            There are no similar posts yet.
            {% endfor %}
          </ul>
          </div>

         

         <!-- Start comment-list -->
          <div class="pt-5">
            {% with comments.count as total_comments %}
            <h3 class="mb-5">{{total_comments}} Comment{{total_comments|pluralize}}</h3>
            {% endwith %}


           {% for comment in comments %}
            <ul class="comment-list">
              <li class="comment">
               
                <div class="comment-body">
                  <h3 class="info">Comment {{forloop.counter}} by {{comment.name}}</h3>

                  <div class="nav-item nav-link disabled" > {{comment.created}}</div>
                  
                  
                  
                  <div class="alert alert-dark" role="alert">
                    <p >{{comment.content|linebreaks}}</p>
                  </div>
                  <hr>

                </div>
                
                {% empty %}
                <h3 class="mb-5">There are no comments.</h3>

              </li>  
                               
                </ul>
                <hr>

                {% endfor %}
             

             
            <!-- END comment-list -->
            {% include "includes/comment_form.html" %}

           


        </article>

        <div class="col-md-12 col-lg-1 order-lg-1">
          <div class="share sticky-top">
            <h3><b>Share By Email</b></h3>
            <ul class="list-unstyled share-article">
              <li><a href="{% url 'blog:post_share' post.id %} "> 
                <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAACXBIWXMAAAsTAAALEwEAmpwYAAACe0lEQVR4nO2ZPWgUQRTHf4nBRKOCjUUKP6r4iUEhWihaik2EFLEwEILaCRIFEa+4ShFsxMJGEFLYCFpopxEJgqIRYmGTxJD4VQiSgBL8wJxMeIFhPMPt3tzuO30/+Dd7OzP/93bu7cwsGIZhGIZhGMbfWAMUgBHgK1BSLufxBXBBvFfFHuCjgqDS6gPQmTb4zcCsgiCq1QzQniYBjxSYj6WHSYPfqsB0bCWaBScVGI6t40kSUFBgOLZcTBVTVGA4tlxMloBKKSp4YjYDsL8AKmvAJ+AiMKRgWi/qHnAeeJ9FAo7IPcuAuwqCvwU0iKeuLBJwzLtvBTCcY/APgOWen94sEjALdHj3tgKPcwjeJX6V52M78DmLBJRkm7nRu9/tu59kGLyrPyu98TeJp0wXQhPAeq+NM3Q/g+BvA83euBuAybxWgpPBTGgCbtYw+GtAY/Dkp/JeCr8FtgXtTwHfIwY+B/QHY+wA3mnZC8wAB4I+dgNvIgQ/BuwM+j4oY6raDH0D+oJ+1gI3gF8p+nNtrpc52OyTsdTuBgeDCr04G54m6OMlsDfoowW4Wi/b4VE5VvNxxeuwrB5/lmnjrt0BDgWFDqkxr+rtPOAHcEkWSiHrgG7grKhbroW4tpelr7o9EJkCeso81aVw+4yjwPS/dCI0BgwAbUuM6347A4zXYPzcE1ASzQOvpVheEQ3KtfkajqsmAaWcZAnAZkDlFBVMWfsLYDUAK4LYWwB7DZLDOqDwvxfBEwoMx9bpJAnYosBwbO0nIUMKTMfSaMLt+ALtKQ4eNeoLsIuUdFbwxUWznPd9VMlq+fT8XLJZD0/8GXBOvBuGYRiGYRgGf/IbjUpi4AEioLwAAAAASUVORK5CYII="
                style="width: 100%;height: 100%;"></a></li>
             
            </ul>
          </div>
        </div>
        <div class="col-lg-3 mb-5 mb-lg-0 order-lg-3">

          <div class="mb-4">
            <a href="https://vimeo.com/342333493" data-fancybox class="video-wrap">
              <span class="play-wrap"><span class="icon-play"></span></span>
              {% if post.image %}
              <img src="{{post.image.url}}" loader="lazy" alt="Image" class="img-fluid rounded">
              {% else %}
              <img src="#" loader="lazy" alt="Image" class="img-fluid rounded">
              {% endif %}
            </a>
          </div>  

          <div class="share floating-block sticky-top">

            <h2 class="mb-3 text-black">Subscribe to Newsletter</h2>
            <p>Far far away behind the word mountains far from.</p>
            <form action="#">
              <input type="email" class="form-control mb-2" placeholder="Enter email">
              <input type="submit" value="Subscribe" class="btn btn-primary btn-block">
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>



  
 


{% endblock content %}

templates/blog/posts/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}My-Blog{% endblock title %}


{% block content %}
<div class="lines-wrap">
    <div class="lines-inner">
      <div class="lines"></div>
    </div>
  </div>
  <!-- END lines -->


  <div class="site-mobile-menu site-navbar-target">
    <div class="site-mobile-menu-header">
      <div class="site-mobile-menu-close">
        <span class="icofont-close js-menu-toggle"></span>
      </div>
    </div>
    <div class="site-mobile-menu-body"></div>
  </div>

 {% include "blog/parts/navbar.html" %}


  <div class="custom-hero">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-6">
          <h1 class="hero-heading">Blog</h1>
          <div  class="line js-line mx-auto mb-3 my-3"></div>
          <p class="sub-text">Development By <b>Moataz Fawzy.</b></p>
          {% if tag %}
          <h2 >Posts Tagged with <b>"{{tag.name}}"</b></h2>
          {% endif %}

        </div>
      </div>
    </div>
  </div>

  
  <div class="section">
    <div class="container">
      <div class="row mb-5">

{% for post in posts %}

        <div class="col-md-6 mb-5 mb-lg-5 col-lg-4">
          <div class="blog_entry">
            {% if post.image %}
            <a href="{{ post.get_absolute_url }}"><img src="{{post.image.url}}" alt="Photo"  loader='lazy' class="img-fluid" style="width: 100%;"></a>

            {% else %}
            <a href="{{ post.get_absolute_url }}"><img src="#" alt="Photo"  loader='lazy' class="img-fluid" style="width: 100%;"></a>

            {% endif %}
            <div class="p-4 bg-white">
              <h3><a href="{{post.get_absolute_url}}">{{ post.title|capfirst|default:"nothing"|markdown }}</a></h3>
             <span class="date"> <b>Publish-Date:</b> <b>{{post.publish}} By {{post.auther}}</b></span>
              <p>{{ post.content|markdown|truncatewords_html:25 }}</p>
              <p class="more"><a href="{{ post.get_absolute_url }}">Read more...</a></p><br>
              <hr>
              {% for tag in post.tags.all %}
              <a href="{% url 'blog:post_list_by_tag' tag.slug %}">{{ tag.name }}</a>,
              {% if forloop.counter|divisibleby:4 and not forloop.last %}
                  <br>
              {% endif %}
          {% endfor %}
          
            </div>
            
          </div>
          
        </div>
        {% endfor %}




      </div>
{% include "blog/parts/pagination.html" with page=posts %}
    </div>
  </div>

  
  
{% endblock content %}

templates/blog/posts/search.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block content %}
{% include "blog/parts/navbar.html" %}
<br>
{% if query %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-8">
            <h1>Posts Containing <b>"{{ query }}"</b></h1>
            <h3>
                {% with results.count as total_results %}
                Found {{ total_results }} result{{ total_results|pluralize }}
                {% endwith %}
                <hr>
            </h3>
            {% for post in results %}
            <article>
                <h4>
                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                </h4>
                {{ post.content|markdown|truncatewords_html:12 }}
                <a href="{{ post.get_absolute_url }}">Read more...</a>
                <hr>
            </article>
            {% empty %}
            <p> </p>
            <div class="alert alert-danger" role="alert">
                There are no results for your query <b>"{{query}}"</b>.
              </div>
            {% endfor %}
            <p><a href="{% url 'blog:post_search' %}">Search Again</a></p>
        </div>
    </div>
</div>
{% else %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-6">
            <h1>Search for posts</h1>
            <form class="form-inline" method="GET" action="{% url 'blog:post_search' %}">
                {{ form.query }}
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </div>
</div>
{% endif %}
{% endblock content %}

templates/blog/posts/share.html
{% extends "blog/base.html" %}

{% block content %}
{% include "blog/parts/navbar.html" %}
<br>
{% if sent %}
<div class="alert alert-success" role="alert">
    <h1 class="alert-heading">E-mail successfully sent!</h1>
    <h4>"{{post.title}}", was successfully sent to "{{form.cleaned_data.to}}".</h4>
    <hr>
    <p class="mb-0"><a href="{% url 'blog:post_list' %}" class="btn btn-light">Back To home</a></p>
</div>
{% else %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-6">
            <div class="share floating-block">
                <h2 class="mb-3 list-group-item active">Share "{{post.title}}" by e-mail</h2>
                <form method="POST">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" value="Send e-mail" class="btn btn-primary btn-block">
                </form>
            </div>
        </div>
    </div>
</div>
{% endif %}
{% endblock content %}